# Run linting, tests and other checks that are safe to run on untrusted code and without secrets.
on: pull_request

name: PR

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
